icook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('orders/', include('orders.urls')),
    path('admin/', admin.site.urls),
]

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'
urlpatterns = [

    path('order_list', views.order_list, name='order_list'),
    path('add_order/<int:id_client>/<int:id_order>', views.add_order, name='add_order'),
    path('checkout', views.CheckOut, name='check_out'),

]

users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import HomeView, RegisterView, OnlineOrderPageView, LogoutView, LoginView

app_name = 'users'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('online_order_page', login_required(OnlineOrderPageView.as_view()), name='online_order'),
    path('register_user', RegisterView.as_view(), name='register_user'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

orders/models.py
from django.utils import timezone

from django.db import models
from users.models import User


class Order(models.Model):
    id_user = models.IntegerField(default=0)
    dish_name = models.CharField(max_length=200, blank=True, null=True)
    dish_price = models.DecimalField(blank=True, null=True, decimal_places=3, max_digits=10)
    dish_description = models.TextField(blank=True, null=True)
    date = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.id_user}, {self.dish_name}, {self.dish_price}'

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cell_phone = models.CharField(max_length=50, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)


    def __str__(self):
        return self.user.get_full_name()


@receiver(post_save, sender=User)
def create_client(sender, instance, created, **kwargs):
    if created:
        Client.objects.create(user=instance)


@receiver(post_save, sender=User)
def update_client(sender, instance, **kwargs):
    instance.client.save()

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class LoginForm(AuthenticationForm):
    pass


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=30, required=True, label="Username", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter your Username'}))
    first_name = forms.CharField(max_length=30, required=False, label="First Name",
                                 widget=forms.TextInput(
                                     attrs={'class': 'form-control', 'placeholder': 'Enter your first name'}))
    last_name = forms.CharField(max_length=30, required=False, label="Last Name",
                                widget=forms.TextInput(
                                    attrs={'class': 'form-control', 'placeholder': 'Enter your last name'}))
    email = forms.EmailField(required=False, label="Email",
                             widget=forms.EmailInput(
                                 attrs={'class': 'form-control', 'placeholder': 'Enter your email'}))
    cell_phone = forms.CharField(label="Phone Number", widget=(
        forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your Phone'})))
    address = forms.CharField(label="Address", widget=(
        forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your Address'})))

    password1 = forms.CharField(label="Password", widget=(
        forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter your password'})))

    password2 = forms.CharField(label="Confirm Password", widget=(
        forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm your password'})))

    class Meta:
        model = get_user_model()
        fields = ["username", "first_name", "last_name",
                  'email', 'cell_phone', 'address', 'password1', 'password2']


class UpdateForm(forms.ModelForm):
    username = forms.CharField(max_length=30, required=True, label="Username", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter your Username'}))
    first_name = forms.CharField(max_length=30, required=False, label="First Name",
                                 widget=forms.TextInput(
                                     attrs={'class': 'form-control', 'placeholder': 'Enter your first name'}))
    last_name = forms.CharField(max_length=30, required=False, label="Last Name",
                                widget=forms.TextInput(
                                    attrs={'class': 'form-control', 'placeholder': 'Enter your last name'}))
    email = forms.EmailField(required=False, label="Email",
                             widget=forms.EmailInput(
                                 attrs={'class': 'form-control', 'placeholder': 'Enter your email'}))
    cell_phone = forms.CharField(label="Phone Number", widget=(
        forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your Phone'})))

    address = forms.CharField(label="Address", widget=(
        forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your Address'})))

    class Meta:
        model = get_user_model()
        fields = ["username", "first_name", "last_name",
                  'email', 'cell_phone', 'address']

orders/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect


from .models import Order



def CheckOut(request):
    """
    Delete a pet changing his status account to False
    """
    total = 0
    orders = Order.objects.filter(status=True)
    for order in orders:
        total = total + order.dish_price

    context = {
        'total':total
    }
    for order in orders:
        order.status = False
        order.id_user = 0
        order.save()


    return render(request,'order/checkout_page.html',context)

def add_order(request, id_client, id_order):
    order = Order.objects.get(id=id_order)
    order.status = True
    order.id_user = id_client
    order.save()
    orders = Order.objects.filter(status=True)
    total = 0
    for order in orders:
        total = total + order.dish_price

    context = {
        'orders': orders,
        'total': total
    }
    return render(request, 'order/order_complete_list.html', context)



@login_required
def order_list(request):
    """
    You can show your pets of your database
    """
    orders = Order.objects.filter(status=True)
    total = 0
    for order in orders:
        total = total + order.dish_price

    context = {
        'orders': orders,
        'total': total
    }

    return render(request, 'order/order_complete_list.html', context)

users/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, FormView, CreateView, RedirectView

from users.forms import RegisterForm, LoginForm


class HomeView(TemplateView):
    """
        This view shows the home page of the app.
    """
    template_name = "base.html"


class RegisterView(CreateView):
    form_class = RegisterForm
    model = User
    template_name = 'registration/register.html'
    success_url = reverse_lazy('users:home')


class LoginView(FormView):
    form_class = LoginForm
    template_name = 'registration/login.html'
    success_url = reverse_lazy('users:home')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            login(self.request, user)
            return super(LoginView, self).form_valid(form)
        else:
            return self.form_invalid(form)


class OnlineOrderPageView(TemplateView):
    """
        This view shows the home page of the app.
    """
    template_name = "order/order.html"


class LogoutView(RedirectView):
    url = reverse_lazy('users:login')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

templates/order/checkout_page.html
{% extends 'order/order.html' %}
{%load static %}
{% block tittle%} Order List {%endblock%}

{% block content %}
    <h3>The total of your purchase was: </h3>
    <h2>{{ total }}</h2>
    <h5>We hope you enjoy your food</h5>
    <a class="btn btn-primary" href="{% url 'users:home' %}">Go back to Home Page</a>
{% endblock content %}

templates/order/order.html
<!DOCTYPE html>
{%load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>BD Restaurant</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Favicons -->
        <link href={% static "img/favicon.ico"%} rel="icon">
        <link href={% static "img/apple-touch-icon.png" %} rel="apple-touch-icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600|Nunito:600,700,800,900" rel="stylesheet">

        <!-- Bootstrap CSS File -->
        <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

        <!-- Libraries CSS Files -->
        <link href="{% static "vendor/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
        <link href="{% static "vendor/animate/animate.min.css" %}" rel="stylesheet">
        <link href="{% static "vendor/owlcarousel/assets/owl.carousel.min.css" %}" rel="stylesheet">
        <link href="{% static "vendor/tempusdominus/css/tempusdominus-bootstrap-4.min.css" %}" rel="stylesheet" />

        <!-- Main Stylesheet File -->
        <link href="{% static "css/style.css" %}" rel="stylesheet">
    </head>

    <body>

        <main id="main">

            <!-- Banner Header Start -->
            <section class="banner-header">
                <div class="logo">
                    <img src="{% static "img/logo.png" %}" />
                </div>
            </section>
            <!-- Banner Header End -->

            <!-- Header Start -->
            <header id="header">
                <div class="container">
                    <nav id="nav-menu-container">
                        <ul class="nav-menu">
                            <li><a href="{% url 'users:home' %}">Home</a></li>
                            <li class="menu-active"><a href="{% url 'users:online_order'  %}">Online Order</a></li>
                            <li><a href="{% url 'users:logout' %}"  >Login / Logout</a></li>
                        </ul>
                    </nav>
                </div>
            </header>
            {% block content %}
            <!-- Menu Section Start -->
            <section id="food-menu">
                <div class="container">
                    <header class="section-header">
                        <h3>delicious Food Menu</h3>
                    </header>
                    <div class="row">
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <div class="single-menu">
                                <img class="img-fluid" src="{% static "img/menu-1.jpg" %}" />
                                <h4>Lorem ipsum</h4>
                                <span>$20.00 / Person</span>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>

                                <a href="{% url 'orders:add_order' id_client=user.id id_order=1 %}">Order</a>

                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <div class="single-menu">
                                <img class="img-fluid" src="{% static "img/menu-2.jpg" %}" />
                                <h4>Curabitur Commodo</h4>
                                <span>$10.00 / Person</span>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                                <a href="{% url 'orders:add_order' id_client=user.id id_order=2 %}">Order Now</a>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <div class="single-menu">
                                <img class="img-fluid" src="{% static "img/menu-3.jpg" %}" />
                                <h4>Proin Tortor</h4>
                                <span>$12.00 / Person</span>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                                <a href="{% url 'orders:add_order' id_client=user.id id_order=3 %}">Order Now</a>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <div class="single-menu">
                                <img class="img-fluid" src="{% static "img/menu-4.jpg" %}" />
                                <h4>Aliquam Erat</h4>
                                <span>$8.00 / Person</span>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                                <a href="{% url 'orders:add_order' id_client=user.id id_order=4 %}">Order Now</a>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <div class="single-menu">
                                <img class="img-fluid" src="{% static "img/menu-5.jpg" %}" />
                                <h4>Curabitur Arcu Massa</h4>
                                <span>$18.00 / Person</span>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                                <a href="{% url 'orders:add_order' id_client=user.id id_order=5 %}">Order Now</a>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <div class="single-menu">
                                <img class="img-fluid" src="{% static "img/menu-6.jpg" %}" />
                                <h4>Vestibulum Fringilla</h4>
                                <span>$15.00 / Person</span>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                                <a href="{% url 'orders:add_order' id_client=user.id id_order=6 %}">Order Now</a>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <div class="single-menu">
                                <img class="img-fluid" src="{% static "img/menu-7.jpg" %}" />
                                <h4>Ullamcorper Facilisis </h4>
                                <span>$10.00 / Person</span>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                                <a href="{% url 'orders:add_order' id_client=user.id id_order=7 %}">Order Now</a>

                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <div class="single-menu">
                                <img class="img-fluid" src="{% static "img/menu-8.jpg" %}" />
                                <h4>Integer Ullamcorper</h4>
                                <span>$22.00 / Person</span>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                                <a href="{% url 'orders:add_order' id_client=user.id id_order=8 %}">Order</a>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3 d-sm-none d-md-block d-lg-none">
                            <div class="single-menu">
                                <img class="img-fluid" src="{% static "img/menu-9.jpg" %}" />
                                <h4>Vestibulum Posuere</h4>
                                <span>$16.00 / Person</span>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                                <a href="{% url 'orders:add_order' id_client=user.id id_order=9 %}">Order Now</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Menu Section End-->

            <!-- Cart Section Start -->

            <!-- Cart Section End -->

           {% endblock content %}

            <!-- Support Section Start -->
            <section id="support">
                <div class="container">
                    <h1>
                        Need Reservations? Call Us 24/7 at +1-234-567-8900
                    </h1>
                </div>
            </section>
            <!-- Support Section end -->

            <!-- Footer Start -->
            <footer id="footer">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="copyright">
                                <p>&copy; Copyright <a href="">Your Site Name</a>. All Rights Reserved</p>
								
								<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
								<p>Template By <a href="https://htmlcodex.com">HTML Codex</a></p>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <form class="form-inline">
                                <label>Get Latest Food Information</label>
                                <div class="form-group">
                                    <input type="email" class="form-control" placeholder="Enter Your Email">
                                </div>
                                <button type="submit" class="btn">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </footer>
            <!-- Footer end -->

            <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

        </main>

       <!-- JavaScript Libraries -->
        <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
        <script src="{% static "vendor/jquery/jquery-migrate.min.js" %}"></script>
        <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
        <script src="{% static "vendor/easing/easing.min.js" %}"></script>
        <script src="{% static "vendor/stickyjs/sticky.js" %}"></script>
        <script src="{% static "vendor/superfish/hoverIntent.js" %}"></script>
        <script src="{% static "vendor/superfish/superfish.min.js" %}"></script>
        <script src="{% static "vendor/owlcarousel/owl.carousel.min.js" %}"></script>
        <script src="{% static "vendor/tempusdominus/js/moment.min.js" %}"></script>
        <script src="{% static "vendor/tempusdominus/js/moment-timezone.min.js" %}"></script>
        <script src="{% static "vendor/tempusdominus/js/tempusdominus-bootstrap-4.min.js" %}"></script>

        <!-- Main Javascript File -->
        <script src="{% static "js/main.js" %}"></script>

    </body>
</html>

templates/order/order_complete_list.html
{% extends 'order/order.html' %}
{%load static %}
{% block tittle%} Order List {%endblock%}

{% block content %}
            <!-- Cart Section Start -->
            <section id="cart">
                <div class="container">
                    <header class="section-header">
                        <h3>Cart</h3>
                    </header>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="table-responsive-sm">
                                <table class="table table-bordered table-hover">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th scope="col">Dish</th>
                                            <th scope="col">Price</th>
                                            <th scope="col">Description</th>
                                            <th scope="col">Date</th>
                                            <th scope="col">Client</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for order in orders %}
                                        <tr>
                                            <th scope="row">{{ order.dish_name }}</th>
                                            <td>{{ order.dish_price }}</td>
                                            <td>{{ order.dish_description }}</td>
                                            <td>{{ order.date }}</td>
                                            {% if order.id_user == user.id %}
                                            <td>{{ user.first_name }}</td>
                                            {% else %}
                                                <td>None</td>
                                            {% endif %}

                                        </tr>
                                     {% endfor %}
                                    </tbody>

                                    <thead class="thead-dark">
                                        <tr>
                                            <th scope="col">Total</th>
                                            <th>
                                               {{ total }}
                                           </th>

                                    </thead>

                                </table>
                            </div>
                            <div class = link >
                                <a class="btn btn-secondary" href="{% url 'orders:check_out' %}">Checkout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Cart Section End -->

    <!-- Menu Section Start -->
            <section id="food-menu">
                <div class="container">
                    <header class="section-header">
                        <h3>delicious Food Menu</h3>
                    </header>
                    <div class="row">
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <div class="single-menu">
                                <img class="img-fluid" src="{% static "img/menu-1.jpg" %}" />
                                <h4>Lorem ipsum</h4>
                                <span>$20.00 / Person</span>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>

                                <a href="{% url 'orders:add_order' id_client=user.id id_order=1 %}">Order</a>

                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <div class="single-menu">
                                <img class="img-fluid" src="{% static "img/menu-2.jpg" %}" />
                                <h4>Curabitur Commodo</h4>
                                <span>$10.00 / Person</span>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                                <a href="{% url 'orders:add_order' id_client=user.id id_order=2 %}">Order Now</a>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <div class="single-menu">
                                <img class="img-fluid" src="{% static "img/menu-3.jpg" %}" />
                                <h4>Proin Tortor</h4>
                                <span>$12.00 / Person</span>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                                <a href="{% url 'orders:add_order' id_client=user.id id_order=3 %}">Order Now</a>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <div class="single-menu">
                                <img class="img-fluid" src="{% static "img/menu-4.jpg" %}" />
                                <h4>Aliquam Erat</h4>
                                <span>$8.00 / Person</span>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                                <a href="{% url 'orders:add_order' id_client=user.id id_order=4 %}">Order Now</a>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <div class="single-menu">
                                <img class="img-fluid" src="{% static "img/menu-5.jpg" %}" />
                                <h4>Curabitur Arcu Massa</h4>
                                <span>$18.00 / Person</span>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                                <a href="{% url 'orders:add_order' id_client=user.id id_order=5 %}">Order Now</a>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <div class="single-menu">
                                <img class="img-fluid" src="{% static "img/menu-6.jpg" %}" />
                                <h4>Vestibulum Fringilla</h4>
                                <span>$15.00 / Person</span>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                                <a href="{% url 'orders:add_order' id_client=user.id id_order=6 %}">Order Now</a>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <div class="single-menu">
                                <img class="img-fluid" src="{% static "img/menu-7.jpg" %}" />
                                <h4>Ullamcorper Facilisis </h4>
                                <span>$10.00 / Person</span>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                                <a href="{% url 'orders:add_order' id_client=user.id id_order=7 %}">Order Now</a>

                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3">
                            <div class="single-menu">
                                <img class="img-fluid" src="{% static "img/menu-8.jpg" %}" />
                                <h4>Integer Ullamcorper</h4>
                                <span>$22.00 / Person</span>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                                <a href="{% url 'orders:add_order' id_client=user.id id_order=8 %}">Order</a>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4 col-lg-3 d-sm-none d-md-block d-lg-none">
                            <div class="single-menu">
                                <img class="img-fluid" src="{% static "img/menu-9.jpg" %}" />
                                <h4>Vestibulum Posuere</h4>
                                <span>$16.00 / Person</span>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
                                <a href="{% url 'orders:add_order' id_client=user.id id_order=9 %}">Order Now</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Menu Section End-->
        {% endblock content %}